# Generated by Django 4.2.6 on 2023-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L001app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalinformation',
            name='fiber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionalinformation',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionalinformation',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionalinformation',
            name='total_carb',
            field=models.IntegerField(default=0),
        ),
    ]
