# Generated by Django 4.2.6 on 2023-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('L001app', '0002_nutritionalinformation_fiber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinformation',
            name='sat_fat',
            field=models.FloatField(),
        ),
    ]
